### PR TITLE
Mac os fix server build

### PR DESCRIPTION
**Pull request by DrEVILish**
Fixes to #132 actually compiles and builds on macOS, fixed lib's -> lua and libarchive. requires installation from `brew install lua` and `brew install libarchive`

### CODE REVIEW

**Comment by reinder** [comment]
It just started the CI/CD to check if everything builds. Else we need to modify it a bit so it works with macOS 12, 13 and 14.

**Comment by DrEVILish** [comment]
I think "Homebrew" changed it's install locations from macOS between Apple Silicon

https://docs.brew.sh/Installation
"The script installs Homebrew to its default, supported, best prefix 
(/opt/homebrew for Apple Silicon,
/usr/local for macOS Intel
/home/linuxbrew/.linuxbrew for Linux)"

You'd probably have to create two build targets for macOS Apple Silicon (ARM64) and Intel.
I don't have an active Intel Mac to test the builds on.

**Comment by reinder** [comment]
Can you verify if it can find hombrew's libarchive if you remove:
```
elseif(APPLE)
  set(LibArchive_INCLUDE_DIRS "/usr/local/opt/libarchive/include")
  set(LibArchive_LIBRARIES "/usr/local/opt/libarchive/lib/libarchive.dylib")
```

**Comment by reinder** [comment]
I'll see if I can add arm64 and intel build for macOS 14 on GitHub actions.

**Comment by DrEVILish** [comment]
macOS Apple Silicon needs the below and this builds correctly
```
elseif(APPLE)
  set(LibArchive_INCLUDE_DIRS "/opt/homebrew/opt/libarchive/include")
  set(LibArchive_LIBRARIES "/opt/homebrew/opt/libarchive/lib/libarchive.dylib")
```

But then I think Apple Intel would need, 
```
elseif(APPLE)
  set(LibArchive_INCLUDE_DIRS "/usr/local/opt/libarchive/include")
  set(LibArchive_LIBRARIES "/usr/local/opt/libarchive/lib/libarchive.dylib")
```

FindLua uses a list of possible paths and "searches" for the correct include path. This might be required for the other 3rd party libraries.

**Comment by reinder** [comment]
Server now builds in macos-14, solved using `find_path` and `find_library` for libarchive and Lua.

Now only the client fails to build on macos-14, did you build it using qt5 or qt6?

**Comment by DrEVILish** [comment]
macOS Client
Qt6.7.0 by the looks of things,
I could try building with Qt5 if that would help?

```
~/traintastic/client/build > cmake ../ -DCMAKE_BUILD_TYPE=Release
-- TRAINTASTIC_VERSION_EXTRA=-dev
-- DEBIAN_PACKAGE_VERSION_EXTRA=
-- The C compiler identification is AppleClang 15.0.0.15000309
-- The CXX compiler identification is AppleClang 15.0.0.15000309
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Python3: /opt/homebrew/Frameworks/Python.framework/Versions/3.12/bin/python3.12 (found version "3.12.4") found components: Interpreter
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Performing Test HAVE_STDATOMIC
-- Performing Test HAVE_STDATOMIC - Success
-- Found WrapAtomic: TRUE
-- Found OpenGL: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/System/Library/Frameworks/OpenGL.framework
-- Found WrapOpenGL: TRUE
-- Found WrapVulkanHeaders: /opt/homebrew/include
-- Found Qt 6.7.0
-- Configuring done (3.1s)
-- Generating done (0.1s)
-- Build files have been written to: /Users/drevilish/traintastic/client/build
```

**Pull request closed without merging**
