### PR TITLE
Z21 fix turnout handling

### PR DESCRIPTION
**Pull request by gfgit**
Needs #81 applied first. Related to #65 

- Fix turnout addressing
- Get turnout info back

### CODE REVIEW

**Comment by gfgit** [comment]
@reinder
Is this working for you?

**Comment by reinder** [comment]
I'll check it with a DR5000, to verify if the Z21 addresses will match with the LocoNet/XpressNet addresses.

**Comment by reinder** [comment]
I just connected to a DR5000 via LocoNet and Z21 using this branch.

image
I connected a turnout to output 15 and 16, using pair/turnout addressing this is address 8.

image

The address scheme is different. LocoNet has flat addresses (one for every output), the Z21 has them in pairs now (aka "turnout" addresses)

This is a common issue, not all command stations support controlling outputs individually, so Traintastic might need better support for that, also most users are "thinking" in turnout/pair addresses. See also #21.

**Comment by reinder** [comment]
See #65

**Comment by reinder** [comment]
@gfgit is there anything you want to add to this PR? or is it ready?

**Comment by gfgit** [comment]
Do you want to wait for #65?
In the meantime I can extract a subset of changes from my PRs which can be already applied.

**Comment by gfgit** [comment]
Rebased onto #81

**Comment by reinder** [comment]
> Do you want to wait for #65? In the meantime I can extract a subset of changes from my PRs which can be already applied.

I'm a bit in doubt of this one, not because of your work, but because how outputs currently work in Traintastic and how turnouts and signals need to be setup for the end user, see #21.

I think it is wise to do some more investigation (in #65) about the differences between the supported command stations/protocols and how their outputs work and how this affects the setup of turnouts and signals.

**Comment by reinder** [comment]
@gfgit due to #21 and #95 I think it is easier to re-apply these changes to the latest master.

**Comment by gfgit** [comment]
Hi Reinder, I've re-applied some changes on top of master.
I have some questions:

1. The turnout address conversion is now done inside `LanXSetTurnout::setAddress()` and `LanXSetTurnout::address()`. Should same conversion happen for `LanXTurnoutInfo` and `LanXGetTurnoutInfo` ? Z21 specifications seems to treat them in same way.
2. When receiving `LanXTurnoutInfo` message, I call `m_outputController->updateOutputValue(...)` inside `EventLoop`. How do I choose `OutputChannel` enum? Z21 spec seems to allow any accessory address.
3. `OutputPair` seems very similar to `TriState`. Which one should I pass?
4. In some other command stations if value is `TriState::Undefined` then the call to `updateOutputValue` is skipped

**Comment by reinder** [comment]
> 1. The turnout address conversion is now done inside LanXSetTurnout::setAddress() and LanXSetTurnout::address(). Should same conversion happen for LanXTurnoutInfo and LanXGetTurnoutInfo ? Z21 specifications seems to treat them in same way.

Yes please, then when using `address()` or `setAddress()` in you don't have to know how how it is mapped in the message, else every time you read `address()` your have to do the correction between the address in message and the "user" address.

> 2. When receiving `LanXTurnoutInfo` message, I call `m_outputController->updateOutputValue(...)` inside `EventLoop`. How do I choose `OutputChannel` enum? Z21 spec seems to allow any accessory address.

The `OutputChannel` must be one of the options listed in `tcb::span<const OutputChannel> Z21Interface::outputChannels() const`, so in this case  `OutputChannel::Accessory`.

> 3. `OutputPair` seems very similar to `TriState`. Which one should I pass?

`OutputPair`, as the `OutputChannel::Accessory` channel uses output pairs.

> 4. In some other command stations if value is `TriState::Undefined` then the call to `updateOutputValue` is skipped

Yes only if that isn't posible protocol wise.

Hoop this help, if unclear please ask :)

**Pull request merged**
